// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AppDate: typeof import('./components/AppDate.vue')['default']
    AppSpinner: typeof import('./components/AppSpinner.vue')['default']
    CarbonPen: typeof import('~icons/carbon/pen')['default']
    CategoryList: typeof import('./components/CategoryList.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    ForumList: typeof import('./components/ForumList.vue')['default']
    PostEditor: typeof import('./components/PostEditor.vue')['default']
    PostList: typeof import('./components/PostList.vue')['default']
    TheNavbar: typeof import('./components/TheNavbar.vue')['default']
    ThreadEditor: typeof import('./components/ThreadEditor.vue')['default']
    ThreadList: typeof import('./components/ThreadList.vue')['default']
    UserProfileCard: typeof import('./components/UserProfileCard.vue')['default']
    UserProfileCardEditor: typeof import('./components/UserProfileCardEditor.vue')['default']
  }
}

export { }
